# Generated by Django 5.2.7 on 2025-10-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image_alter_project_live_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.PositiveIntegerField(default=66734),
            preserve_default=False,
        ),
    ]
