# Generated by Django 5.2.7 on 2025-10-11 10:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_contact_message_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(default='tazul.png', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
