# Generated by Django 5.2.7 on 2025-10-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(default='no comment'),
            preserve_default=False,
        ),
    ]
