# Generated by Django 5.2.7 on 2025-11-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contact_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
