# Generated by Django 5.2.7 on 2025-11-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='53263', max_length=11),
            preserve_default=False,
        ),
    ]
