# Generated by Django 5.2.7 on 2025-11-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_contact_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
