# Generated by Django 5.2.7 on 2025-11-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_deploy_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
