# Generated by Django 5.2.7 on 2025-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_backend_deploy_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='backend_deploy_link',
        ),
    ]
