# Generated by Django 5.2.7 on 2025-11-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_backend_deploy_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='backend_deploy_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
