# Generated by Django 5.2.7 on 2025-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_live_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
