# Generated by Django 5.2.7 on 2025-11-11 13:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(max_length=200)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('backend_deploy_link', models.URLField(blank=True, null=True)),
                ('github_frontend_link', models.URLField(blank=True, null=True)),
                ('github_backend_link', models.URLField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
